# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5adb2a08a6e2ba083bf69a89a29998929a833c5c2a1e9dbf718debb29231b81d0b9ea4a93e3aa53583d2d9ae296fe6a695cd04cd1548b0695b7102fa8384d8d3

test:
  secret_key_base: 6802fc2af13e60388cc1cc3d2ce35fc5b81d877fd0649750db1ec36fc56b25037d12733e561db82fe174d3abb40682d16f121de09a17afaa2a371accf31496d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
